server:
  port: 9001

eureka:
  instance:
    hostname: localhost # eureka服务端的实例名称
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false # false 表示不向注册中心注册自己
    fetch-registry: false # false 表示自己端就是注册中心，维护服务实例，并不需要去检索服务
    service-url:
      default-zone: http://localhost:${server.port}/eureka  # 设置与Eureka Server交互的地址查询服务和注册服务

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    compatibility-verifier:
      enabled: false
    bus:
      trace:
        enabled: true
feign: